server:
  port: 8080

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
security:
  user:
    password: none
  oauth2:
    resource:
      filter-order: 3

## 自定义jsonwebtoken密钥信息
config:
  oauth2:
    key-store: jwt.jks
    secret-key: mySecretKey
    alias: jwt

## Mybatis 配置
mybatis:
  typeAliasesPackage: cn.youkai.micro.domain
  mapperLocations: classpath:mapper/*.xml

## Mysql
spring:
  datasource:
    url: jdbc:mysql://39.108.11.254:3306/world?characterEncoding=utf8
    username: root
    password: Jgxy@1234#
    driver-class-name: com.mysql.jdbc.Driver